name: site-dev

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
    paths:
      - site/**
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'dev'
    paths:
      - site/**
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/orijen-udf-site
  CONTEXT: site
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Login to Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{env.CONTEXT}}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}